<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>UnofficialModuKeymapStudio</AssemblyName>
    <RootNamespace>ModuKeymapStudio</RootNamespace>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <InformationalVersion>1.0.0</InformationalVersion>
    <AssemblyTitle>Unofficial MODU Keymap Studio</AssemblyTitle>
    <Product>Unofficial MODU Keymap Studio</Product>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ModuKeymapStudio.Core\ModuKeymapStudio.Core.csproj" />
  </ItemGroup>
</Project>
